import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import Footer from "./components/Footer/Footer";
import ResponsiveNav from "./components/Navgiation/ResponsiveNav";
import "./globals.css";

const barlow_condensed = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Burger Bite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow_condensed.className}>
        <ResponsiveNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
